const apiRoutes = {
  auth: {
    register: "/api/V1/auth/Register",
    login: "/api/V1/auth/login",
    newcode: "/api/V1/auth/newcode",
    forgetPassword: "/auth/forgetPassword",
    verifyOtp: "/auth/forgetPassword/verifyOtp",
    updatePass: "/auth/forgetPassword/updatePass",
    user: "/users/profile",
  },
  admin: {
    aboutUpdating: "/api/V1/admin/aboutUpdating",
    allUsers: "/api/V1/admin/alluseres",
    creatAnnouncement: "/api/V1/admin/creatAnnouncement",
    creatVisit: "/api/V1/admin/creatVisit",
    creatDeal: "/api/V1/admin/creatdeal",
    creatSlider: "/api/V1/admin/creatslider",
    creatTeam: "/api/V1/admin/creatteam",
    dashboard: "/api/V1/admin/dashboard",
    deleteVisit: "/api/V1/admin/deleteVisit",
    deleteDeal: "/api/V1/admin/deletedeal",
    deleteTeam: "/api/V1/admin/deleteteam",
    getAllRequests: "/api/V1/admin/getAllRequests",
    getAllSliders: "/api/V1/admin/getAllSliders",
    getAllVisits: "/api/V1/admin/getAllVisits",
    getAllDeals: "/api/V1/admin/getAlldeals",
    getAllTeam: "/api/V1/admin/getAllteam",
    getByUid: "/api/V1/admin/getbyUid",
    getByStateCode: "/api/V1/admin/getbystatecode",
    initiateSetting: "/api/V1/admin/initiateSetting",
    inprogress: "/api/V1/admin/inprogress",
    notconfirmed: "/api/V1/admin/notconfirmed",
    notconfirmedannouncements: "/api/V1/admin/notconfirmedannouncements",
    promotToAdmin: "/api/V1/admin/promotToAdmin",
    rejectAnnounce: "/api/V1/admin/rejectannounce",
    search: "/api/V1/admin/search",
    updateVisits: "/api/V1/admin/updateVisits",
    updateAnnoun: "/api/V1/admin/updateannoun",
    updateDeal: "/api/V1/admin/updatedeal",
    updateSlider: "/api/V1/admin/updateslider",
    updateTeam: "/api/V1/admin/updateteam",
    updateUser: "/api/V1/admin/updateuser",
    uploadLogo: "/api/V1/admin/uploadLogo",
    uploadPhotos: "/api/V1/admin/uploadPhotos",
    uploadSliderPhotos: "/api/V1/admin/uploadsliderPhotos",
    verifyAnnounce: "/api/V1/admin/varifyannounce",
    deleteSlider: "/api/V1/admin/deleteslider"
  }
};
export default apiRoutes;